### ISSUE TITLE
Instructions for REV Client + FRC Driver Station/Control System

### ISSUE THREAD

**Issue by secmancer** [Team3512/csweb.frc3512.com#26]
We could either link users to the respective documentation for each or write out separate tutorials for using the Rev Client, Driver Station, RoboRIO Imager, etc. This would also heavily benefit non-software students, so they can have a main place to know where to look for help.

**Comment by calcmogul** [comment]
Do not write your own documentation for using the control system hardware. Contribute it to the official docs at https://github.com/wpilibsuite/frc-docs instead. roboRIO imaging and basic DS usage is already documented, iirc, so if they're insufficient, make an issue or PR and let the NI, FIRST, and WPILib people bicker about it.

REV also has REV Hardware Client docs at https://docs.revrobotics.com/sparkmax/rev-hardware-client/getting-started-with-the-rev-hardware-client. If they suck, file an issue or PR at https://github.com/REVrobotics/SPARK-MAX-Documentation.

I want all the docs in this repo that are applicable to more than just 3512 to get upstreamed eventually so the team has less to maintain. The only thing that wouldn't be, really, is the intro to C++ module since the official docs assume programming competence (not a great assumption, and you could argue teaching programming is in scope, but it's more work than they want to do).

**Comment by secmancer** [comment]
Noted.
